import { DATA_SCHEDULE_MODULE } from 'data_schedule';
import { AhuDimens } from 'core_designsystem';

export const FEATURE_SCHEDULE_MODULE: string = `${DATA_SCHEDULE_MODULE}/feature/schedule`;
export const FEATURE_SCHEDULE_CARD_CORNER: number = AhuDimens.cardCorner;
export { ScheduleSetupPage } from './src/main/ets/schedule/ScheduleSetupPage';
export { WeeklySchedulePage } from './src/main/ets/schedule/WeeklySchedulePage';
